### ISSUE TITLE
Reparsing already parsed text causes duplicate or removed characters

### ISSUE THREAD

**Issue by comatosebunny** [max-kamps/jpdb-browser-reader#20]
Previous issue with な being removed between words was fixed, but now な gets removed after a word but before ellipses. Examples in discord. 呑気な・・・・・・。changed to 呑気・・・・・・。Edit: This is happening in ttu, vertical text.

**Comment by sdbversini** [comment]
More context from what we discovered (to make it easier to find again):
- happens in horizontal text too, and with/without ellipses, so this is not the issue
- seems to happen on reparsing text already parsed
- in her case, it was from disabling/re-enabling the extension
- something weird happens if doing another cycle of disable/reenable in the original sentence ( 「本当にボニファティウス様は厄介な……」), where the 様 gets duplicated
